#!/bin/bash

BlueCyan='\e[5;36m'
Xark='\e[0m'
ungu='\033[35m'
yellow='\e[33m'
WhiteBe='\e[5;37m'
GreenBe='\e[5;32m'
BlueCyan='\e[5;36m'
White="\033[97;1m"
Green="\033[92;1m"
Cyan="\033[96;1m"
Xark='\e[0m'
BG_BLU="\033[44;1m" # BG BIRU
clear
function cek-bw() {
clear 
baris_panjang
echo -e "$ungu      • BANDWITH MONITOR •         \e[0m"
baris_panjang
echo -e "" 
echo -e " 1. Lihat Total Bandwith Tersisa"
echo -e " 2. Tabel Penggunaan Setiap 5 Menit"
echo -e " 3. Tabel Penggunaan Setiap Jam"
echo -e " 4. Tabel Penggunaan Setiap Hari"
echo -e " 5. Tabel Penggunaan Setiap Bulan"
echo -e " 6. Tabel Penggunaan Setiap Tahun"
echo -e " 7. Tabel Penggunaan Tertinggi"
echo -e " 8. Statistik Penggunaan Setiap Jam"
echo -e " 9. Lihat Penggunaan Aktif Saat Ini"
echo -e " 10. Lihat Trafik Penggunaan Aktif Saat Ini [5s]"
echo -e "" 
echo -e " [\e[31m•0\e[0m] \e[31mBACK TO MENU${Xark}"
echo -e " [\e[31m•x\e[0m] Keluar"
echo -e "" 
baris_panjang
echo -e ""
read -p " Select menu : " opt
echo -e ""
case $opt in
1)
clear 
baris_panjang
echo -e "$ungu • TOTAL BANDWITH SERVER TERSISA • \e[0m"
baris_panjang
echo -e ""

vnstat

echo -e ""
baris_panjang
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
cek-bw
;;

2)
clear 
baris_panjang
echo -e "$ungu • TOTAL BANDWITH SETIAP 5 MENIT • \e[0m"
baris_panjang
echo -e ""

vnstat -5

echo -e ""
baris_panjang
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
cek-bw
;;

3)
clear 
baris_panjang
echo -e "$ungu   • TOTAL BANDWITH SETIAP JAM •   \e[0m"
baris_panjang
echo -e ""

vnstat -h

echo -e ""
baris_panjang
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
cek-bw
;;

4)
clear 
baris_panjang
echo -e "$ungu  • TOTAL BANDWITH SETIAP HARI •   \e[0m"
baris_panjang
echo -e ""

vnstat -d

echo -e ""
baris_panjang
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
cek-bw
;;

5)
clear 
baris_panjang
echo -e "$ungu  • TOTAL BANDWITH SETIAP BULAN •  \e[0m"
baris_panjang
echo -e ""

vnstat -m

echo -e ""
baris_panjang
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
cek-bw
;;

6)
clear 
baris_panjang
echo -e "$ungu  • TOTAL BANDWITH SETIAP TAHUN •  \e[0m"
baris_panjang
echo -e ""

vnstat -y

echo -e ""
baris_panjang
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
cek-bw
;;

7)
clear 
baris_panjang
echo -e "$ungu    • TOTAL BANDWITH TERTINGGI •   \e[0m"
baris_panjang
echo -e ""

vnstat -t

echo -e ""
baris_panjang
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
cek-bw
;;

8)
clear 
baris_panjang
echo -e "$ungu • STATISTIK TERPAKAI SETIAP JAM • \e[0m"
baris_panjang
echo -e ""

vnstat -hg

echo -e ""
baris_panjang
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
cek-bw
;;

9)
clear 
baris_panjang
echo -e "$ungu     • LIVE BANDWITH SAAT INI •    \e[0m"
baris_panjang
echo -e   " Press [ Ctrl+C ] • To-Exit"
echo -e ""

vnstat -l

echo -e ""
baris_panjang
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
cek-bw
;;

10)
clear 
baris_panjang
echo -e "$ungu• LIVE TRAFIK PENGGUNAAN BANDWITH •\e[0m"
baris_panjang
echo -e ""

vnstat -tr

echo -e ""
baris_panjang
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
cek-bw
;;

0)
menu
;;
x)
exit
;;
*)
menu
;;
esac
}
function baris_panjang() {
  echo -e "${BlueCyan} ———————————————————————————————————————${Xark}"
}
function ATAS() {
  echo -e     "${ungu}                FEATURES               ${Xark} "
}

function  FIXX() {
  echo -e  " ${BG_BLU}               MENU FIXX              ${Xark}"
}


function  CLEAR() {
  echo -e  " ${BG_BLU}               MENU CLEAR             ${Xark}"
}


function  INFORMATION() {
  echo -e  " ${BG_BLU}              INFORMATION             ${Xark}"
}


function  OTHER() {
  echo -e  " ${BG_BLU}                OTHER                 ${Xark}"
}


function Create_Bot_Notif() {
  create-bot-notif
}


function Info_Port() {
  prot
}


function Registrasi_Ip_Vps() {
echo -e "${Cyan} ANDA HARUS MENGHUBUNGI ADMIN-${Xark} "
echo -e "${Cyan}      TERLEBIH DAHULU ${Xark} "
echo -e "
echo -e "${Cyan} Untuk Membeli source / Menyewa ${Xark} "
echo ""
echo -e ${White} whatsapp : 083851216065 ${Xark} "
}

# Banner 
function Banner(){
clear
baris_panjang
ATAS
baris_panjang
}


function Menu_Lambofgod() {
baris_panjang
echo -e ""
echo -e "  1.) Running Service    "  
echo -e "  2.) Restart Service    " 
echo -e "  3.) Auto Reboot " 
echo -e "  4.) Monitoring         " 
echo -e "  5.) SpeedTest "
echo -e "  6.) Delete All Account Exp "
baris_panjang
FIXX
baris_panjang
echo -e "  7.) Change Banner      "  
echo -e "  8.) Change Domain      "  
echo -e "  9.) Fixx Haproxy       "  
echo -e " 10.) Fixx Domain        "  
echo -e " 11.) Auto Pointting     "  
echo -e " 12.) Install Udp        "  
echo -e " 13.) Backup Bot Telegram   "
baris_panjang
CLEAR
baris_panjang
echo -e " 14.) Clear Cache "
echo -e " 15.) Clear Logs "
echo -e " 16.) Clear Cache File "
baris_panjang
INFORMATION
baris_panjang
echo -e " 17.) Info Service Port  "
echo -e " 18.) Information System "
echo -e " 19.) Check Bandwidth Usage "
baris_panjang
echo -e " 20.) Back to Menu"
echo -e "  x . EXIT "
echo -e ""
baris_panjang
echo -e ""

}

function Select_Menu() {
read -p "Select From Options [1-19 or x] :  " Ltt
case $Ltt in
1) clear ; run ;;
2) clear ; reset ;;
3) clear ; autoreboot ;;
4) clear ; gotop ;;
5) clear ; speedtest ;;
6) clear ; xp ;;
7) clear ; nano /etc/banner.txt ;;
8) clear ; change-domain ;;
9) clear ; fixhap ;;
10) clear ; fixcert ;;
11) clear ; cf ;;
12) clear ; UDEPE ;;
13) clear ; mbot ;;
14) clear ; clearcache ;;
15) clear ; clearlog ;;
16) clear ; delet-cache-file ;;
17) clear ; Info_Port ;;
18) clear ; neo ;;
19) clear ; cek-bw ;;
20) clear ; menu ;;
x) exit ;;
*) m-ftr ;;
esac
}


Banner
Menu_Lambofgod
Select_Menu