#!/bin/bash
clear

yellow="\033[0;33m"
ungu="\033[0;35m"
Xark="\033[0m"
BlueCyan="\033[5;36m"

baris_panjang() {
  echo -e "${BlueCyan} ——————————————————————————————————— ${Xark}"
}

vip_Banner() {
  clear
  baris_panjang
  echo -e "${ungu}               ZIDAN TUNNELING      ${Xark}"
  baris_panjang
}

Sc_Credit() {
  sleep 1
  baris_panjang
  echo -e "${ungu}  Terimakasih Telah Menggunakan ${Xark}"
  echo -e "${ungu}          Script Credit ${Xark}"
  echo -e "${ungu}              ZIDAN TUNNELING ${Xark}"
  baris_panjang
  exit 1
}

vip_Banner
echo ""
echo -e "${yellow}        MEMBER VLESS ${Xark}"
baris_panjang
echo "  User        Expired      Quota   IP"
baris_panjang

mkdir -p /etc/vless
touch /etc/vless/.vless.db

if grep -qE "^### " /etc/vless/.vless.db; then
  grep -E "^### " /etc/vless/.vless.db | awk '{print "  "$2, $3, $5"GB", $6"IP"}' | column -t | sort | uniq
else
  echo "  Tidak ada akun VLESS"
fi

baris_panjang
Sc_Credit