#!/bin/bash

echo '{'
echo '  "status": "success",'
echo '  "total_users": '"$(awk -F: '$3 >= 1000 && $1 != "nobody" {print $1}' /etc/passwd | wc -l)"','
echo '  "users": ['

first=1

while IFS=: read -r AKUN x ID gid desc home shell; do

  if [[ "$ID" -ge 1000 && "$AKUN" != "nobody" ]]; then

    exp=$(chage -l "$AKUN" | grep "Account expires" | awk -F": " '{print $2}')
    status=$(passwd -S "$AKUN" 2>/dev/null | awk '{print $2}')

    if [[ "$status" == "L" ]]; then
      status_text="LOCKED"
    else
      status_text="UNLOCKED"
    fi

    [[ $first -eq 0 ]] && echo ','

    echo -n "    {
      \"username\": \"$AKUN\",
      \"expired\": \"$exp\",
      \"status\": \"$status_text\"
    }"

    first=0
  fi

done < /etc/passwd

echo ''
echo '  ]'
echo '}'
