#!/bin/bash
######################################
MYIP=$(curl -sS ipv4.icanhazip.com)
######################################
#IPVPS=$(curl -s ipv4.icanhazip.com)
#ISP=$(cat /etc/xray/isp)
#CITY=$(cat /etc/xray/city)
#domain=$(cat /etc/xray/domain)
#RAM=$(free -m | awk 'NR==2 {print $2}')
#MODEL=$(cat /etc/os-release | grep -w ID | head -n1 | sed 's/=//g' | sed 's/"//g' | sed 's/ID//g')

#uptime="$(uptime -p | cut -d " " -f 2-10)"
#cpu_usage1="$(ps aux | awk 'BEGIN {sum=0} {sum+=$3}; END {print sum}')"
#cpu_usage="$((${cpu_usage1/\.*} / ${coREDiilik:-1}))"
#cpu_usage+=" %"

clear


# // Gettings Info
function upp(){
clear
cd /usr/local/
rm -rf sbin
rm -rf /usr/bin/enc
cd
mkdir /usr/local/sbin
dateFromServer=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
biji=`date +"%Y-%m-%d" -d "$dateFromServer"`
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
clear
fun_bar() {
    CMD[0]="$1"
    CMD[1]="$2"
    (
        [[ -e $HOME/fim ]] && rm $HOME/fim
        ${CMD[0]} -y >/dev/null 2>&1
        ${CMD[1]} -y >/dev/null 2>&1
        touch $HOME/fim
    ) >/dev/null 2>&1 &
    tput civis
    echo -ne "  \033[0;33mPlease Wait Loading \033[1;37m- \033[0;33m["
    while true; do
        for ((i = 0; i < 18; i++)); do
            echo -ne "\033[0;32m# "
            sleep 0.1s
        done
        [[ -e $HOME/fim ]] && rm $HOME/fim && break
        echo -e "\033[0;33m]"
        sleep 1s
        tput cuu1
        tput dl1
        echo -ne "  \033[0;33mPlease Wait Loading \033[1;37m- \033[0;33m["
    done
    echo -e "\033[0;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
    tput cnorm
}
res1() {
    wget https://raw.githubusercontent.com/ZidanKhofifi/vip/main/Cdy/menu.zip
    wget -q -O /usr/bin/enc "https://raw.githubusercontent.com/F4-RIS/v7/main/Enc/encrypt" ; chmod +x /usr/bin/enc
    7z e -paskykenza123 menu.zip
    unzip menu.zip
    chmod +x menu/*
    enc menu/*
    mv menu/* /usr/local/sbin
    rm -rf menu
    rm -rf menu.zip
    rm -rf update.sh
    rm -rf uodate
    rm -rf /root/menu
    rm -rf /root/menu.zip
    rm -rf /root/update.sh
    rm -rf /root/welcome
    rm -rf /root/change-limit-xray
    rm -rf /root/change-ip-limit
    rm -rf /root/change-domain
    rm -rf /root/fixhap
    rm -rf /root/fixcert
    rm -rf /root/xtra-menu
    rm -rf /root/others
    rm -rf /root/manager
    rm -rf /root/m-ftr
    rm -rf /root/m-bkp
    rm -rf /root/m-bot
    rm -rf /root/m-ssh
    rm -rf /root/m-ssr
    rm -rf /root/m-vme
    rm -rf /root/m-vle
    rm -rf /root/m-tro
    rm -rf /root/mbot
    rm -rf /root/m-panel
    rm -rf /root/add-bot-notif
    rm -rf /root/add-ip
    rm -rf /root/add-ssh
    rm -rf /root/add-vme
    rm -rf /root/add-vle
    rm -rf /root/add-ssr    
    rm -rf /root/auto-kill
    rm -rf /root/autobackup
    rm -rf /root/autoreboot
    rm -rf /root/clearcache
    rm -rf /root/clearlog
    rm -rf /root/backup
    rm -rf /root/restore
    rm -rf /root/cek-ssh
    rm -rf /root/cek-ssr
    rm -rf /root/cek-vle
    rm -rf /root/cek-vme
    rm -rf /root/cek-tro
    rm -rf /root/member-ssh
    rm -rf /root/member-vme
    rm -rf /root/member-vle
    rm -rf /root/member-tro
    rm -rf /root/membee-ssr
    rm -rf /root/user-ssh
    rm -rf /root/user-ssr
    rm -rf /root/user-vme
    rm -rf /root/user-vle
    rm -rf /root/user-tro
    rm -rf /root/renew-ssh
    rm -rf /root/renew-ssr
    rm -rf /root/renew-vme
    rm -rf /root/renew-vle
    rm -rf /root/renew-tro
    rm -rf /root/trial-ssh
    rm -rf /root/trial-vle
    rm -rf /root/trial-ssr
    rm -rf /root/trial-vme
    rm -rf /root/trial-tro
    rm -rf /root/delexp
    rm -rf /root/xp
    rm -rf /root/member
    rm -rf /root/tendang
    rm -rf /root/speedtest
    rm -rf /root/run
    rm -rf /root/reset
    rm -rf /root/gotop
    rm -rf /root/prot
    rm -rf /root/mullog
    rm -rf /root/Lt-on-off
    rm -rf /root/limitspeed
    rm -rf /root/limitssh-ip
    rm -rf /root/lock-vmess
    rm -rf /root/lock-xray-ip
    rm -rf /root/lock
    rm -rf /root/unlock
    rm -rf /root/ganti-ip-ssh
    rm -rf /root/ganti-ip-vmess
    rm -rf /root/ganti-ip-vless
    rm -rf /root/ganti-ip-trojan
    rm -rf /root/del-ssh
    rm -rf /root/del-vme
    rm -rf /root/del-vle
    rm -rf /root/del-ssr
    rm -rf /root/del-tro
    rm -rf /root/create-bot-notif
    rm -rf /root/hapus-bot-notif
    rm -rf /root/ceklim
    rm -rf /root/about
    rm -rf /root/limit-on-off
    rm -rf /root/killtrial
    rm -rf /root/hapus-bot
    rm -rf /root/delet-cache-file
    rm -rf /root/del-bot-notif
    rm -rf /root/change-vmess-qouta
    rm -rf /root/change-vless-qouta
    rm -rf /root/change-trojan-qouta
    rm -rf /root/cf
    rm -rf /root/bot
    rm -rf /root/add-tro
    rm -rf /root/add-ip-bot
    rm -rf /root/about
    rm -rf /root/UDEPE
    rm -rf /root/Bot-Domain
    rm -rf /root/menu-noobzvpns
}
netfilter-persistent
clear
echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e " \e[1;97;101m             UPDATE SCRIPT         \e[0m"
echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e ""
echo -e "  \033[1;91m update script service\033[1;37m"
fun_bar 'res1'
echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e ""
echo -e "\033[92mWait in  3 sec..\033[0m"
sleep 3
menu
}

######################################
# // USERNAME IZIN IPP
rm -f /usr/bin/user
username=$(curl -sS https://raw.githubusercontent.com/ZidanKhofifi/vip/main/izin-ip-sandz | grep $MYIP | awk '{print $2}')
echo "$username" >/usr/bin/user
rm -f /usr/bin/e
valid=$(curl -sS https://raw.githubusercontent.com/ZidanKhofifi/vip/main/izin-ip-sandz | grep $MYIP | awk '{print $3}')
echo "$valid" > /usr/bin/e

clear
######################################
# // DETAIL ORDER IZIN IP
username=$(cat /usr/bin/user)
oid=$(cat /usr/bin/ver)
exp=$(cat /usr/bin/e)
######################################
clear
# // DAYS LEFT
d1=$(date -d "$valid" +%s)
d2=$(date -d "$today" +%s)
certifacate=$(((d1 - d2) / 86400))
clear
######################################
# Status ExpiRED Active | Geo Project
Info="(${green}AKTIF${NC})"
Error="(${RED}EXPIRED${NC})"
today=`date -d "0 days" +"%Y-%m-%d"`
Exp1=$(curl -sS https://raw.githubusercontent.com/ZidanKhofifi/vip/main/izin-ip-sandz | grep $MYIP | awk '{print $3}')
if [[ $today < $Exp1 ]]; then
sts="${Info}"
else
sts="${Error}"
fi
echo -e "\e[32mloading...\e[0m"
clear
# // GETTINGS SYSTEM
ssh_service=$(/etc/init.d/ssh status | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)

dropbear_service=$(/etc/init.d/dropbear status | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)

haproxy_service=$(systemctl status haproxy | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)

xray_service=$(systemctl status xray | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)

nginx_service=$(systemctl status nginx | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)

clear
######################################
# // RUNNING SSH
######################################
if [[ $ssh_service == "running" ]]; then 
   status_ssh="\033[92;1mON${NC}"
else
   status_ssh="\033[91;1mOFF${NC} "
fi
######################################
# // RUNNING WEBSOCKET
######################################
ssh_ws=$( systemctl status ws | grep Active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g' )
if [[ $ssh_ws == "running" ]]; then
    status_ws_epro="\033[92;1mON${NC}"
else
    status_ws_epro="\033[91;1mOFF${NC} "
fi
######################################
# RUNNING HAPROXY
######################################
if [[ $haproxy_service == "running" ]]; then 
   status_haproxy="\033[92;1mON${NC}"
else
   status_haproxy="\033[91;1mOFF${NC} "
fi
######################################
# RUNNING XRAY
######################################
if [[ $xray_service == "running" ]]; then 
   status_xray="\033[92;1mON${NC}"
else
   status_xray="\033[91;1mOFF${NC} "
fi
######################################
# RUNNING NGINX
######################################
if [[ $nginx_service == "running" ]]; then 
   status_nginx="\033[92;1mON${NC}"
else
   status_nginx="\033[91;1mOFF${NC} "
fi
######################################
# RUNNING DROPBEAR
######################################
if [[ $dropbear_service == "running" ]]; then 
   status_dropbear="\033[92;1mGOOD${NC}"
else
   status_dropbear="\033[91;1mCRAZY${NC} "
fi

# VMESS
vma=$(grep -c '^### ' /etc/vmess/.vmess.db 2>/dev/null)

# VLESS
vla=$(grep -c '^### ' /etc/vless/.vless.db 2>/dev/null)

# TROJAN
trb=$(grep -c '^#! ' /etc/trojan/.trojan.db 2>/dev/null)

# SHADOWSOCKS
ssa=$(grep -c '^#!# ' /etc/shadowsocks/.shadowsocks.db 2>/dev/null)

# SSH
ssh1=$(awk -F: '$3 >= 1000 && $1 != "nobody" {print $1}' /etc/passwd | wc -l)

function 878-Zsandz_Banner() {
clear
echo -e "\033[96;1m┌─────────────────────────────────────────────────┐\033[0m "
echo -e "\e[96;1m│\e[0m \033[41;1;97;1m              ZIDAN  VIP TUNNELING             \033[0m \e[96;1m│\e[0m"
echo -e "\033[96;1m└─────────────────────────────────────────────────┘\033[0m "
}

function Service_System_Operating() {
echo -e "\033[96;1m┌─────────────────────────────────────────────────┐\033[0m "
echo -e "\033[96;1m│\e[97m SYSTEM          : $(cat /etc/os-release | grep -w ID | head -n1 | sed 's/=//g' | sed 's/"//g' | sed 's/ID//g')     \033[0m "
echo -e "\033[96;1m│\e[97m RAM             : $(free -m | awk 'NR==2 {print $2}')    \033[0m "
echo -e "\033[96;1m│\e[97m UPTIME          : $(uptime -p | cut -d " " -f 2-10)\033[0m "
echo -e "\033[96;1m│\e[97m IP VPS          : $(curl -s ipv4.icanhazip.com)     \033[0m "
echo -e "\033[96;1m│\e[97m ISP             : $(cat /etc/xray/isp)    \033[0m "
echo -e "\033[96;1m│\e[97m DOMAIN          : $(cat /etc/xray/domain)    \033[0m "
echo -e "\033[96;1m└─────────────────────────────────────────────────┘\033[0m"
}

function Service_Status() {
echo -e "\033[96;1m┌─────────────────────────────────────────────────┐\033[0m "
echo -e "\033[96;1m│\e[0m\e[33m PROXY :\e[0m $status_haproxy  \e[0m|\e[33m NGINX :\e[0m $status_nginx  \e[0m|\e[33m SSHWS :\e[0m $status_ws_epro \e[0m|  $status_dropbear  \e[96;1m│ \e[0m "
echo -e "\033[96;1m└─────────────────────────────────────────────────┘\033[0m "
}

function Check_Bandwidth_Usage() {
echo -e "\033[96;1m┌─────────────────────────────────────────────────┐${NC}"
echo -e "\033[96;1m│\e[0m\e[33mSSH:\e[0m $ssh1 \e[0m| \e[33mVMESS:\e[0m $vma \e[0m| \e[33mVLESS:\e[0m $vla \e[0m| \e[33mTROJAN:\e[0m $trb \e[0m| \e[33mSS:\e[0m $ssa \e[96;1m│\e[0m"
echo -e "\033[96;1m└─────────────────────────────────────────────────┘${NC}"
}

function Details_Clients_Name() {
echo -e "\033[96;1m     ┌───────────────────────────────────────┐\033[0m "
echo -e "\033[96;1m              \e[97m VERSION : \033[33m47.9 Libev                  \e[0m "     
echo -e "\033[96;1m              \e[97m DEV     : \033[33mZIDAN VPN               \e[0m "
echo -e "\033[96;1m              \e[97m CLIENTS : \033[33m$username                 \e[0m "
echo -e "\033[96;1m              \e[97m EXPIRED : \033[33m$certifacate Hari Tersisa                         \e[0m "
echo -e "\033[96;1m              \e[97m STATUS SC : \033[33m$sts                 \e[0m "
echo -e "\033[96;1m     └───────────────────────────────────────┘\033[0m "
}

function Acces_Use_Command() {
echo -e "\033[96;1m┌─────────────────────────────────────────────────┐\033[0m "
echo -e "\033[96;1m│ \e[34m1.)\e[93m☞ \e[97m SSH/OPENVPN         \e[34m6.)\e[93m☞ \e[97m BOT TELEGRAM    \e[96;1m│\e[0m "   
echo -e "\033[96;1m│ \e[34m2.)\e[93m☞ \e[97m XRAY MANAGER        \e[34m7.)\e[93m☞ \e[97m UPDATE SCRIPT   \e[96;1m│\e[0m "
echo -e "\033[96;1m│ \e[34m3.)\e[93m☞ \e[97m NEW NOOBVPNS        \e[34m8.)\e[93m☞ \e[97m BACKUP RESTOR   \e[96;1m│\e[0m "
echo -e "\033[96;1m│ \e[34m4.)\e[93m☞ \e[97m XRAY TROJAN         \e[34m9.)\e[93m☞ \e[97m FEATURES        \e[96;1m│\e[0m "
echo -e "\033[96;1m│ \e[34m5.)\e[93m☞ \e[97m SS-R Libev.         \e[31mx.)\e[93m☞ \e[91m EXIT            \e[96;1m│\e[0m "
echo -e "\033[96;1m└─────────────────────────────────────────────────┘\033[0m "
}

function Select_Display() {
echo
read -p "Select From option [1/9 or x] :  " bangsat
case $bangsat in
1) clear ; m-ssh ;; # menu ssh
2) clear ; m-xray ;; # menu vmess
3) clear ; m-noobz ;; # menu Noobvpns
4) clear ; m-tro ;; # menu trojan
5) clear ; m-ssr ;; # menu sadowsocks
6) clear ; bot ;; # menu bot telegram
7) clear ; update-sc ;; # update Script
8) clear ; m-bkp ;; # menu backup
9) clear ; m-ftr ;; # menu managers
x) welcome ;; # Back To Home Welcome
esac
}


878-Zsandz_Banner
Service_System_Operating
Service_Status
Check_Bandwidth_Usage
Details_Clients_Name
Acces_Use_Command
Select_Display




