#!/bin/bash

Minutes="$1"

if [[ -z "$Minutes" ]]; then
  echo '{"status":"error","message":"Usage: trial-ssh-api minutes"}'
  exit 1
fi

if ! [[ "$Minutes" =~ ^[0-9]+$ ]]; then
  echo '{"status":"error","message":"minutes must be number"}'
  exit 1
fi

domain=$(cat /etc/xray/domain)
IP=$(curl -sS ipv4.icanhazip.com)
ISP=$(cat /etc/xray/isp 2>/dev/null)
CITY=$(cat /etc/xray/city 2>/dev/null)

Login="Trial-$(tr -dc X-Z0-9 </dev/urandom | head -c4)"
Pass="1"
iplimit="99"

mkdir -p /etc/kyt/limit/ssh/ip/
echo "$iplimit" > /etc/kyt/limit/ssh/ip/$Login

useradd -e "$(date -d "1 days" +"%Y-%m-%d")" -s /bin/false -M "$Login"
echo -e "$Pass\n$Pass\n" | passwd "$Login" >/dev/null 2>&1

mkdir -p /etc/ssh
touch /etc/ssh/.ssh.db
sed -i "/^#ssh# $Login /d" /etc/ssh/.ssh.db
echo "#ssh# $Login $Pass 0 $iplimit trial-${Minutes}-minutes" >> /etc/ssh/.ssh.db

cat > /var/www/html/ssh-$Login.txt <<END
TRIAL SSH OPENVPN ACCOUNT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Username      : $Login
Password      : $Pass
Domain        : $domain
IP VPS        : $IP
ISP           : $ISP
City          : $CITY
Limit IP      : $iplimit
Expired       : $Minutes Minutes
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SSH WS        : $domain:80@$Login:$Pass
SSH SSL       : $domain:443@$Login:$Pass
UDP Custom    : $domain:1-65535@$Login:$Pass
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Payload WS:
GET / HTTP/1.1[crlf]Host: [host][crlf]Connection: Upgrade[crlf]User-Agent: [ua][crlf]Upgrade: websocket[crlf][crlf]

Payload Enhanced:
PATCH / HTTP/1.1[crlf]Host: $domain[crlf]Host: bug.com[crlf]Connection: Upgrade[crlf]User-Agent: [ua][crlf]Upgrade: websocket[crlf][crlf]
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
END

echo "userdel -f \"$Login\"; rm -f /etc/kyt/limit/ssh/ip/$Login /var/www/html/ssh-$Login.txt; sed -i '/^#ssh# $Login /d' /etc/ssh/.ssh.db" | at now + "$Minutes" minutes >/dev/null 2>&1

cat <<EOF
{
  "status": "success",
  "type": "trial",
  "username": "$Login",
  "password": "$Pass",
  "domain": "$domain",
  "ip": "$IP",
  "isp": "$ISP",
  "city": "$CITY",
  "ip_limit": "$iplimit",
  "expired_minutes": "$Minutes",
  "ssh_ws": "$domain:80@$Login:$Pass",
  "ssh_ssl": "$domain:443@$Login:$Pass",
  "udp_custom": "$domain:1-65535@$Login:$Pass",
  "account_url": "https://$domain:81/ssh-$Login.txt",
  "payload_ws": "GET / HTTP/1.1[crlf]Host: [host][crlf]Connection: Upgrade[crlf]User-Agent: [ua][crlf]Upgrade: websocket[crlf][crlf]",
  "payload_enhanced": "PATCH / HTTP/1.1[crlf]Host: $domain[crlf]Host: bug.com[crlf]Connection: Upgrade[crlf]User-Agent: [ua][crlf]Upgrade: websocket[crlf][crlf]"
}
EOF
